version: '3.7'

services:

  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minha_cena
    volumes:
      - pgdata:/data/postgres

#  app:
#    build: .
#    container_name: backend_minha_cena
#    ports:
#      - 3080:3080
#    volumes:
#      - .:/usr/apps
#    links:
#      - database
#    depends_on:
#      - database


volumes:
  pgdata:
    driver: local
