version: '3.7'

services:

  database:
    image: postgres
    container_name: database_minha_cena
    restart: always
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=password
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build: .
    container_name: minha_cena
    ports:
      - 3080:3080
    environment:
      - DATABASE_URL=postgresql://root:password@database:5432/minha_cena
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
