version: '3.7'

services:

  database:
    image: postgres
    container_name: database_minha_cena
    restart: always
    ports:
      - '5439:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=minha_cena
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - '8080:80'
    environment:
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_DEFAULT_EMAIL=root@minhacena.com
    depends_on:
      - database

  app:
    image: minhacena/minha-cena-backend_app
    container_name: minha_cena
    ports:
      - 80:3080
    environment:
      - DATABASE_URL=postgresql://root:password@database:5432/minha_cena
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
